name: extension:create
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run compiler
      run: npm run compile
    - name: Run extenion create command
      run: npm run test:create
