name: command:preview
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run compiler
      run: yarn compile
    # - name: Run `extension preview` command (TODO)
    #   run: yarn test:preview
